### ISSUE TITLE
Xlib.error.DisplayConnectionError: Can't connect to display ":1": b'Maximum number of clients reached'

### ISSUE THREAD

**Issue by champcui** [MCZhi/Expert-Prior-RL#4]
There was a new issues and couldn't save expert_data when run that command 'scl run --envision expert_recording.py left_turn --samples 40'. 

`Exception in thread Thread-2064:
Traceback (most recent call last):
  File "/home/cjp/anaconda3/envs/smarts/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/cjp/HUANGZHIYU/Expert-Prior-RL-main/.venv/lib/python3.7/site-packages/pynput/_util/__init__.py", line 210, in run
    self._run()
  File "/home/cjp/HUANGZHIYU/Expert-Prior-RL-main/.venv/lib/python3.7/site-packages/pynput/keyboard/_xorg.py", line 545, in _run
    super(Listener, self)._run()
  File "/home/cjp/HUANGZHIYU/Expert-Prior-RL-main/.venv/lib/python3.7/site-packages/pynput/_util/xorg.py", line 382, in _run
    self._display_stop = Xlib.display.Display()
  File "/home/cjp/HUANGZHIYU/Expert-Prior-RL-main/.venv/lib/python3.7/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/home/cjp/HUANGZHIYU/Expert-Prior-RL-main/.venv/lib/python3.7/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/home/cjp/HUANGZHIYU/Expert-Prior-RL-main/.venv/lib/python3.7/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":1": b'Maximum number of clients reached'
`

**Comment by MCZhi** [comment]
Looks like it's a problem with the `pynput` package, which takes the keyboard inputs. I suggest reinstalling the package and making sure it works well on your system.

**Comment by JovialZH** [comment]
Hello, I would like to ask what is the installed version of pyput and the installed version of ray. The number of return values ​​of my on close method is incorrect
